/approach_service_server:
  ros__parameters:
    scan_topic: "/scan"
    odom_topic: "/diffbot_base_controller/odom"
    cmd_vel_topic: "/diffbot_base_controller/cmd_vel_unstamped"
    odom_frame: "odom"
    intensity_threshold: 8000.0